# Dependabot configuration for version updates

version: 2
updates:
  - package-ecosystem: "npm" # Use npm for JavaScript projects
    directory: "/" # Root directory where package.json is located
    schedule:
      interval: "weekly" # Set Dependabot to check for updates weekly
